<?php

/**
 * @file
 * Primary module hooks for éadimeo_dco module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function adimeo_dco_theme($existing, $type, $theme, $path)
{
  /* Not used but should be used */
}

/**
 * Implements hook_cron().
 */
function adimeo_dco_cron()
{
  $nodes = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties([
    'type' => 'event',
    'status' => TRUE
  ]);
  $count = 0;
  $now = time();
  foreach ($nodes as $node) {
    $node_date = strtotime($node->get('field_date_end')->value);
    if($node_date < $now) {
      $node->setPublished(FALSE);
      $node->save();
      $count++;
    }
  }
  \Drupal::messenger()->addMessage($count .' node(s) updated');
}
